#ifndef __DEFAULTS_H
#define __DEFAULTS_H

#define DEFAULT_SCALE_FACTOR 0.75f

#define DEFAULT_FRAMERATE 1
#define DEFAULT_BLOCK_SIZE 7
#define DEFAULT_DISP_COUNT 128

#define DEFAULT_D12_MAX_DIFF 10
#define DEFAULT_SPECKLE_RANGE 7
#define DEFAULT_SPECKE_WS 60
#define DEFAULT_PF_CAP 1
#define DEFAULT_UNIQ_RATIO 0

#endif
