#ifndef __DEFAULTS_H
#define __DEFAULTS_H

#define DEFAULT_BLUR_RADIUS 1
#define DEFAULT_SCALE_FACTOR 2.0f / 3

#define DEFAULT_FRAMERATE 2
#define DEFAULT_BLOCK_SIZE 3
#define DEFAULT_DISPARITY_COUNT 64
#define DEFAULT_MIN_DISPARITIES 0

#define DEFAULT_LEFT_CAM_INDEX 1
#define DEFAULT_RIGHT_CAM_INDEX 2

#endif
