%YAML:1.0
---
# Camera definition stuff
cams:
    framerate: 2
    id: [1, 2]
    size: [1280, 960]
# Stereo vision stuff
# > REQUIRED
matcher:
    scaleFactor: 0.75
    blockSize: 7
    numDisparities: 128
    disp12MaxDiff: 10
    speckleRange: 7
    speckleWindowSize: 60
    preFilterCap: 1
    uniquenessRatio: 0
