%YAML:1.0
---
# Camera definition stuff
cams:
    framerate: 2
    id: [1, 2]
    size: [1280, 720]
# Stereo vision stuff
# > REQUIRED
matcher:
    scaleFactor: 0.65
    alg: 0
    disp12MaxDiff: 10
    speckleRange: 7
    speckleWindowSize: 60
    preFilterCap: 63
    mode: 2
