%YAML:1.0
---
# Camera definition stuff
video:
    sources:
        - name: webcam
          id: 0
          on: 0
        - name: left
          id: 1
          res: [1280, 960]
        - name: right
          id: 2
          res: [1280, 960]
          on: 0
    defaults:
        fps: 30
        res: [1280, 720]
        on: 1
        scale: 0.75
    contrib: 0.75
# Stereo vision stuff
# > REQUIRED
matcher:
    source: [Left, Right]
    alg: 0
    disp12MaxDiff: 10
    speckleRange: 7
    speckleWindowSize: 60
    preFilterCap: 63
    mode: 2
test:
    t1: {a: 2}
    t2: {a: 1, b: 2, c: 3}
