%YAML:1.0
---
# Camera definition stuff
video:
  src: [1, 2]
  name: [Left, Right]
  fps: 30
  src-rez: [1280, 720]
  scale: 0.65
  contrib: 0.75
  blur: 5

# Stereo vision stuff
# > REQUIRED
matcher:
  preFilterCap: 63
  mode: 1
  main_cam: 1

#Occupancy Grid parameters (in cm):
og:
  cameraHeight: 51.7525 #50.165 #camera height (in cm)
  robotWidth: 10.66 #robot width (in cm)
  robotLength: 10.66 #robot length (in cm)
  clearance: 2.25 #clearance from obstacles (in cm)
  occupancySize: [200, 200] #[width, height]
  xRange: [-100, 100]
  yRange: [0, 250]
  zRange: [0, 500]
  r: 7 #7 #r param for the sigmoid adjustment
  c: 0.2 #0.02 #c param for the sigmoid adjustment
  deltaN: 55 #deltaN param for the probability computation
  nt: -3.6 #unknown occupancy threshold (probability < nt -> occupancy is unknown)
  lt: -3 #occupied threshold (probability >= lt -> cell is occupied)
  deltaH: 20 #deltaH param for the probability computation
  wN: 0.5 #weight for the probability based on number of points in cell
  wH: 0.5 #weight for the probability based on obstacle height
