%YAML:1.0
---
# Camera definition stuff
video:
    src: [0, 1]
    name: [Left, Right]
    fps: 30
    src-rez: [1280, 720]
    scale: 0.5
    contrib: 0.75
    blur: 7
# Stereo vision stuff
# > REQUIRED
matcher:
    disp12MaxDiff: 10
    speckleRange: 7
    speckleWindowSize: 60
    preFilterCap: 63
    mode: 2
    uniquenessRatio: 0
    main_cam: 1
